### ISSUE TITLE
README lacks install instructions.

### ISSUE THREAD

**Issue by JonHolt** [MCluck90/pomo#2]
I want to use this on my Mac. Is that supported?

**Comment by mikecluck** [comment]
Good call out. I believe it should work on Mac. Try this:

```shell
git clone https://github.com/MCluck90/pomo
cd pomo
cargo build --release
```

Then if you want to run it from anywhere you'll need to add `pomo/target/release` to your PATH or copy `pomo/target/release/pomo` and `pomo/target/release/resources` to somewhere in your path.

Since I'm too lazy to put together a real installer, I'll add this stuff to the README later

**Comment by JonHolt** [comment]
```
error[E0599]: no method named `image_path` found for mutable reference `&mut notify_rust::notification::Notification` in the current scope
  --> src/main.rs:61:14
   |
61 |             .image_path(&format!("file:///{}", resources.to_str().unwrap()))
   |              ^^^^^^^^^^ method not found in `&mut notify_rust::notification::Notification`
```
I'm getting this error, are there dependencies I need to install first?

**Comment by mikecluck** [comment]
Weird. `cargo build` should have downloaded all of the dependencies. Try running `rustup update` to make sure you're running the latest stable version of Rust

**Comment by mikecluck** [comment]
Double weird. I just configured Linux to cross-compile to Mac. I'm getting the same error. I'll see if I can figure out what's up

**Comment by mikecluck** [comment]
Looks like it's a [problem with the underlying dependency](https://github.com/hoodie/notify-rust#macos-support). Just remove the line with `image_path` and it should work fine. I'll see if I can only include that line if compiling on other OSes

**Comment by mikecluck** [comment]
All right, last comment for now I swear. I just pushed up a commit that I believe addresses this. Would you mind pulling it down and trying it?

**Comment by JonHolt** [comment]
```
➜  pomo git:(master) cargo build --release
   Compiling pomo v0.1.0 (/Users/jholt/source/personal/pomo)
error[E0308]: mismatched types
  --> src/main.rs:36:5
   |
35 |   ) -> Result<(), notify_rust::error::Error> {
   |        ------------------------------------- expected `std::result::Result<(), notify_rust::error::Error>` because of return type
36 | /     Notification::new()
37 | |         .appname("Pomo")
38 | |         .summary("Break time!")
39 | |         .body(body_message)
40 | |         .timeout(Timeout::Milliseconds(6000))
41 | |         .show()
   | |_______________^ expected `()`, found struct `notify_rust::macos::NotificationHandle`
   |
   = note: expected enum `std::result::Result<(), _>`
              found enum `std::result::Result<notify_rust::macos::NotificationHandle, _>`
```
Wish I could be more help, but I still haven't learned any rust.

**Comment by mikecluck** [comment]
Weak. Testing cross-compiling is a pain when you don't own the matching hardware :joy: I appreciate you testing it for me. I pushed up another commit that may fix it

**Comment by JonHolt** [comment]
that built. I'll try it out and get back to you.

**Comment by JonHolt** [comment]
It runs! Is the system alert supposed to make a sound? Right now it doesn't and without sound mac alerts are weirdly subtle. But that seems like a different issue to me. Thanks for the help getting it running.

**Comment by mikecluck** [comment]
Awesome! Glad it got sorted out. I want to add a sound but have been too lazy lol So for now that's intended behavior
